### ISSUE TITLE
Alpine linux support

### ISSUE THREAD

**Issue by root-io** [retrohacker/getos#32]
```
> mongodb-prebuilt@4.5.5 postinstall /myproject/node_modules/mongodb-prebuilt
> node install.js

/myproject/node_modules/mongodb-download/index.js:80
				throw e;
				^

Error: No unique release file found!
    at /myproject/node_modules/getos/index.js:136:21
    at FSReqWrap.oncomplete (fs.js:82:15)

```

I guess Alpine linux is not yet supported ? :p (related to #16)

**Comment by retrohacker** [comment]
Hey @root-io,

First, thank you so much for opening this issue and including the output.

The ambitious goal of getos is to have a wide support of distributions.This goal requires a community effort, with people contributing test cases and passing code for their favorite distributions. I personally have spent quite a bit of time tracking down release files to populate this with, but they aren't 100% since it isn't practical to test hundreds of distributions individually by hand. With that in mind, Alpine Linux absolutely can be supported.

If you are interested in contributing and can add your local `alpine-release` file to https://github.com/retrohacker/getos/tree/master/tests I would be happy to accept a PR that gets it passing!

**Comment by root-io** [comment]
Hey @retrohacker no worries, I sent a PR (https://github.com/retrohacker/getos/pull/34) regarding this issue. I don't know how to get the `release` version.

```
Fetching Distributions... [OK!]
Fetching versions of Alpine... [OK!]
Building version 3.3 of Alpine... [OK!]
Running container... [OK!]
Output from version 3.3 of Alpine: 
{"os":"linux","dist":"Alpine Linux"}
Fetching versions of Debian... [OK!]
Building version 7.3 of Debian... [OK!]
Running container... [OK!]
Output from version 7.3 of Debian: 
{"os":"linux","dist":"Debian","release":"7.3","codename":"wheezy"}
Building version 7.4 of Debian... [OK!]
Running container... [OK!]
Output from version 7.4 of Debian: 
{"os":"linux","dist":"Debian","release":"7.4","codename":"wheezy"}
Building version 7.5 of Debian... [OK!]
Running container... [OK!]
Output from version 7.5 of Debian: 
{"os":"linux","dist":"Debian","release":"7.5","codename":"wheezy"}
Building version 7.6 of Debian... [OK!]
Running container... [OK!]
Output from version 7.6 of Debian: 
{"os":"linux","dist":"Debian","release":"7.6","codename":"wheezy"}
Fetching versions of Fedora... [OK!]
Building version 20 of Fedora... [FAILED!]
Fetching versions of Ubuntu... [OK!]
Building version 13.10 of Ubuntu... [FAILED!]
Building version 14.04 of Ubuntu... [OK!]
Running container... [OK!]
Output from version 14.04 of Ubuntu: 
{"os":"linux","dist":"Ubuntu Linux","codename":"trusty","release":"14.04"}
```

Also, Fedora 20 and Ubuntu 13.10 seem to fail.

Last question, is that normal that [this line](https://github.com/retrohacker/getos/blob/master/tests/runTest.js#L71) removes the Dockerfile of your project ?

**Comment by retrohacker** [comment]
Landed in https://github.com/retrohacker/getos/pull/34

**Comment by retrohacker** [comment]
shipped in https://github.com/retrohacker/getos/commit/652ef32599cdea60b6828013aac8d3d8d363246a
